language: node_js

deploy:
  provider: npm
  email:
    secure: azv42nCfDFOnVvsN5U6ghmlay0t+dKdQM+766L9Qh9v4frX7xPWn+kEAvajLMHsa00wI2wbdNkf8wIDLC6neG67omjfUQItAwqcfgXHfZJXicjd5zHhLbAW4qm/LW7i0PqC0f5LvlVi50stDlS22rKGydvN5UqZc5HVaJJ6BGLphuuE+II3akaQu/6/D2qqWeS/QJ8VeWocsNXNEc1Rc66ZkxClhHypQCfdfuUiMf0+D3KU3C1cpsbo/Ys3pQZhgm4rFr8C+3BYf14emU+AXPmaTvirPB/JV+nUm0C2rHJ7vydKMjy992WLFfU7RtdH1rAQnrLivJzbyVdf1XeaClwMd4agEItotI/aOvfi050OJrpJL07EqeQ1sOYzsza6IZ6QjB+4Uj3mRBNgSNZS4nHUPjq4yPRNrUrzjgf6ZI5wbQ0WoFRvzr8nFuxSpggj4SF4R4sg1YJlmwHwFAXiKa/tKj5dw6xXpAGXqqVTSqngBDpfbYrhkk/SKlRGGSEZrzIjSdvtZ+EuyFhVDUKvHEzN2lEKLwKRTKblmfKsHdwmjGnPT28YduEUDRFtVMJy7tTouoOxYtUxUI7P5b5mVQKqCM5qRRAFItL4J519DAU5wNQ4fV0N3IPiAR1NzQzaElzHQKEISw5VP2p5gXAVCIRWM4ksuBvlE/DZBwBdgpoE=
  api_key:
    secure: RXs8+nVzdaZLHTJRVAmceSUAcmgGN5aSry34IWl8h4Yd06qSV+kxyEEGoLew6gRqV+ZEupHgfEmoTsrwtGGr3c+b/IDK2W5/JhkQsaBEXykQb+0fQechJHVJb5w09RE7cb6kA+AvE09j4MZyBMtHyxWPJ2Q6lwaD9NLt3KNkFKOXP1kxKMP9r11zERYyNYjIQsx6nW9nZWV1s/tYoaVKjcuT2VH8LFhRN8mroGfvpf8ccjiY3sMuxMZbipmhEt20OzKX4ZW1N4AYq/kluF9nhsQR9/cJ707DwBp5wx/BRItFNQpQUE3dA5U2MH9/hyW6aZ5DM6jmTDPJbJXSW70rUzHGx5x0AYSLdPJ7ImpHSdqBVWvNapCpAdTxyDxOq8nAdXNHfnlmwGTjIvNrdIuMWfqLV+1oPntwODhffkA1b6oKb4HVRP4gWcu8r3MA0TFoioYoPNLpaMEqQSDVUP9FqPCLA8kxn8LhoDokHZ28k6500NCDLFQBAierS7PRPX7WtIi0jz1MIVZ8VwgUxn4E9cXPK/2iJ8mj2AKbIGMetAkkAJchP8VCXS9fu/h1sSkUVMfAxAw7siiWmofqQb2gW/g+zZ25RfcyoQim1tEwOEkqIiMcC5oWuVFuV1Wn2f9ZJAo4JLy5XY0Rne75pEru9Xcmw/FPk+wEtiWYZEYbn8w=
  on:
    tags: true

notifications:
  email:
    recipients:
    - type@codenaem.co
    on_success: change
    on_failure: always